services:
  - type: web
    name: affiliate-video-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_URL
        sync: false
      - key: PIXABAY_API_KEY
        sync: false
      - key: NGROK_AUTH_TOKEN
        sync: false
      - key: COLAB_SECRET
        value: affiliatebot_v7_secret
      - key: VIDEO_ENGINE
        value: auto
      - key: DEFAULT_PLATFORM
        value: tiktok
      - key: PORT
        value: "5000"
